import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const dist=path.join(root,'dist');
const origin='https://archcell-atelier.aunabbas572.chatgpt.site';
const pages={studio:['The Studio — Archcell','A Lahore architecture and interior design practice shaped by a decade of residential work.'],services:['Architecture & Interior Design Services — Archcell','Explore architecture, interiors and complete working drawing services from Archcell, Lahore.'],process:['Our Process — Archcell','From your first idea to a coordinated drawing collection: discover the Archcell design process.'],projects:['The Project Collection — Archcell','Explore Archcell’s illustrative portfolio of residential architecture and interiors.'],drawings:['The Drawing Room — Archcell','Browse project collections of plans, elevations, structural, electrical, plumbing and interior drawings.'],contact:['Start Your Project — Archcell','Create a demo project enquiry for your home, interiors or working drawings.'],privacy:['About This Preview — Archcell','How the demo enquiry form works, reference photography and information about this website preview.'],'404':['Page Not Found — Archcell','Return to Archcell and discover the project collection.']};
const header=`<header class="site-header" id="site-header"><a class="brand" href="/" aria-label="Archcell home"><span class="brand-icon"><img src="/assets/archcell-logo.jpg" alt="" /></span><span>ARCHCELL<small>ARCHITECTURE & INTERIORS</small></span></a><nav aria-label="Main navigation"><a href="/projects/">Selected work <span>06</span></a><a href="/studio/">The studio</a><a href="/services/">Services</a><a href="/process/">Our process</a><a href="/drawings/">Drawing room</a></nav><a class="header-cta" href="/contact/">Start a project <span>↗</span></a><button class="menu-button" aria-label="Open navigation" aria-expanded="false"><span></span><span></span></button></header><div class="mobile-nav" inert><a href="/projects/">Selected work</a><a href="/studio/">The studio</a><a href="/services/">Services</a><a href="/process/">Our process</a><a href="/drawings/">Drawing room</a><a href="/contact/">Start a project ↗</a><span>LAHORE, PAKISTAN</span></div>`;
const footer=`<footer class="site-footer section-pad"><div class="footer-top"><span class="eyebrow">ARCHCELL / LAHORE, PAKISTAN</span><a class="text-link" href="/contact/">Tell us about your project <span>↗</span></a></div><p class="footer-statement">A place to call <em>yours.</em></p><nav class="footer-navigation" aria-label="Footer navigation"><a href="/projects/">Selected work</a><a href="/studio/">The studio</a><a href="/services/">Services</a><a href="/process/">Our process</a><a href="/drawings/">Drawing room</a><a href="/contact/">Contact</a></nav><div class="footer-bottom"><a href="/" class="footer-wordmark">ARCHCELL</a><p>Architecture & interiors.<br>Thoughtfully, from the ground up.</p><a href="#" class="back-top">BACK TO TOP ↑</a></div><div class="footer-fine"><span>© 2026 Archcell</span><span>Design preview. Illustrative projects and drawings; not for construction.</span><a href="/privacy/">About this preview</a><button id="credits-button">Photography credits ↗</button></div></footer>`;
let home=fs.readFileSync(path.join(dist,'index.html'),'utf8');
home=home.replace(/<header class="site-header"[\s\S]*?<main id="main-content">/,header+'\n<main id="main-content">');
home=home.replace(/<footer class="site-footer[\s\S]*?<\/footer>/,footer);
home=home.replace('href="#studio">Discover our approach','href="/process/">Discover our approach');
if(!home.includes('href="/pages.css"'))home=home.replace('<link rel="stylesheet" href="/style.css" />','<link rel="stylesheet" href="/style.css" />\n<link rel="stylesheet" href="/pages.css" />');
if(!home.includes('src="/pages.js"'))home=home.replace('<script src="/app.js" defer></script>','<script src="/app.js" defer></script>\n<script src="/pages.js" defer></script>');
home=home.replace(/\s*<link rel="canonical"[^>]*>/g,'');
home=home.replace('</head>',`<link rel="canonical" href="${origin}/" />\n</head>`);
fs.writeFileSync(path.join(dist,'index.html'),home);
for(const [slug,[title,description]]of Object.entries(pages)){
 let html=home.replace(/<title>[\s\S]*?<\/title>/,`<title>${title}</title>`).replace(/<meta name="description" content="[^"]*" \/>/,`<meta name="description" content="${description}" />`).replace('<body>','<body class="interior-page">').replace(/<main id="main-content">[\s\S]*?<\/main>/,`<main id="main-content">${fs.readFileSync(path.join(root,'pages',slug+'.html'),'utf8')}${footer}</main>`).replace(/<link rel="canonical"[^>]*>/,`<link rel="canonical" href="${origin}/${slug==='404'?'404.html':slug+'/'}" />`);
 const target=slug==='404'?path.join(dist,'404.html'):path.join(dist,slug,'index.html');fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,html);
}
console.log('Updated homepage and generated 8 complete supporting pages.');
