import { defineField, defineType } from 'sanity';

export const homePage = defineType({
  name: 'homePage',
  title: 'Homepage',
  type: 'document',
  fields: [
    defineField({
      name: 'hero',
      title: 'Hero',
      type: 'object',
      options: { collapsible: true, collapsed: false },
      fields: [
        defineField({ name: 'eyebrow', title: 'Eyebrow', type: 'string' }),
        defineField({ name: 'titleTop', title: 'Headline (first line)', type: 'string' }),
        defineField({ name: 'titleEm', title: 'Headline (italic word)', type: 'string' }),
        defineField({ name: 'paragraph', title: 'Supporting line', type: 'text', rows: 2 }),
        defineField({ name: 'toplineLeft', title: 'Top line (left)', type: 'string' }),
        defineField({ name: 'toplineRight', title: 'Top line (right)', type: 'string' }),
        defineField({ name: 'footerLeft', title: 'Bottom line (left)', type: 'string' }),
        defineField({ name: 'image', title: 'Background image', type: 'image', options: { hotspot: true } }),
      ],
    }),
    defineField({
      name: 'intro',
      title: 'Intro section',
      type: 'object',
      options: { collapsible: true, collapsed: true },
      fields: [
        defineField({ name: 'eyebrow', title: 'Eyebrow', type: 'string' }),
        defineField({ name: 'heading', title: 'Heading', type: 'string' }),
        defineField({ name: 'headingSpan', title: 'Heading (second line)', type: 'string' }),
        defineField({ name: 'paragraph', title: 'Paragraph', type: 'text', rows: 3 }),
        defineField({ name: 'linkLabel', title: 'Link label', type: 'string' }),
      ],
    }),
    defineField({
      name: 'work',
      title: 'Selected work section',
      type: 'object',
      options: { collapsible: true, collapsed: true },
      fields: [
        defineField({ name: 'eyebrow', title: 'Eyebrow', type: 'string' }),
        defineField({ name: 'heading', title: 'Heading', type: 'string' }),
        defineField({ name: 'headingEm', title: 'Heading (italic word)', type: 'string' }),
        defineField({ name: 'aside', title: 'Side note', type: 'string' }),
        defineField({ name: 'noteLabel', title: 'Note label', type: 'string' }),
        defineField({ name: 'noteText', title: 'Note text', type: 'string' }),
      ],
    }),
    defineField({
      name: 'interlude',
      title: 'Image interlude',
      type: 'object',
      options: { collapsible: true, collapsed: true },
      fields: [
        defineField({ name: 'eyebrow', title: 'Eyebrow', type: 'string' }),
        defineField({ name: 'heading', title: 'Heading', type: 'string' }),
        defineField({ name: 'headingEm', title: 'Heading (italic line)', type: 'string' }),
        defineField({ name: 'label', title: 'Corner label', type: 'string' }),
        defineField({ name: 'image', title: 'Image', type: 'image', options: { hotspot: true } }),
      ],
    }),
    defineField({
      name: 'drawingRoom',
      title: 'Drawing room section',
      type: 'object',
      options: { collapsible: true, collapsed: true },
      fields: [
        defineField({ name: 'eyebrow', title: 'Eyebrow', type: 'string' }),
        defineField({ name: 'heading', title: 'Heading', type: 'string' }),
        defineField({ name: 'headingEm', title: 'Heading (italic line)', type: 'string' }),
        defineField({ name: 'paragraph', title: 'Paragraph', type: 'text', rows: 3 }),
        defineField({ name: 'linkLabel', title: 'Link label', type: 'string' }),
        defineField({ name: 'teaserLabels', title: 'Teaser labels', type: 'array', of: [{ type: 'string' }] }),
      ],
    }),
    defineField({
      name: 'studio',
      title: 'Studio section',
      type: 'object',
      options: { collapsible: true, collapsed: true },
      fields: [
        defineField({ name: 'eyebrow', title: 'Eyebrow', type: 'string' }),
        defineField({ name: 'heading', title: 'Heading', type: 'string' }),
        defineField({ name: 'headingEm', title: 'Heading (italic line)', type: 'string' }),
        defineField({ name: 'paragraphOne', title: 'Paragraph one', type: 'text', rows: 3 }),
        defineField({ name: 'paragraphTwo', title: 'Paragraph two', type: 'text', rows: 3 }),
        defineField({ name: 'image', title: 'Image', type: 'image', options: { hotspot: true } }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: 'Homepage' }) },
});
